name: Update Git Submodules

on:
  schedule:
    - cron: '0 3 * * *'  # Run every day at 3 AM UTC
  workflow_dispatch:      # Allow manual triggering

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update all submodules to latest on master
        run: |
          git submodule foreach '
            echo "Updating $name..."
            git checkout master || echo "Already on master"
            git pull origin master
          '

      - name: Commit and push if there are changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          if git diff --cached --quiet; then
            echo "No submodule updates."
          else
            git commit -m "updated - $(date +"%Y-%m-%d %H:%M:%S")"
            git push
          fi
